# Generated by Django 3.2.14 on 2022-07-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.FileField(upload_to='file'),
        ),
    ]
