# Generated by Django 3.2.14 on 2022-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_uploadedfile_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.FileField(upload_to='media/'),
        ),
    ]
