# Generated by Django 3.2.14 on 2022-07-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_alter_uploadedfile_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
