# Generated by Django 3.2.14 on 2022-07-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_auto_20220718_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
