# Generated by Django 3.2.14 on 2022-07-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0007_uploadedfile_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='auth.user'),
            preserve_default=False,
        ),
    ]
